### PR TITLE
update code to work with current golang / wasm

### PR DESCRIPTION
**Pull request by spreeker**
I liked this code to figure out how S2 works. Gave it an update to work with current go version `go1.15.5 linux/amd64`.
updated with my local `wasm_exec.js`.

### CODE REVIEW

**Comment by akhenakh** [comment]
Thanks for the PR, I'll review it ASAP

**Comment by akhenakh** [comment]
thanks

**Comment by akhenakh** [comment]
@spreeker Since your update the rectangle and polygon lookup doesn't work:
```
coverShape. localhost:8080:94:12
(0xcece0,0x80a700) wasm_exec.js:50:14
panic: JavaScript error: Bounds are not valid. wasm_exec.js:50:14
<empty string> wasm_exec.js:50:14
goroutine 6 [running]: wasm_exec.js:50:14
syscall/js.Value.Call(0x7ff8000100000005, 0x0, 0x856a2, 0x8, 0x0, 0x0, 0x0, 0x8a2030, 0x8a2000) wasm_exec.js:50:14
	/usr/local/Cellar/go/1.15/libexec/src/syscall/js/js.go:400 +0x34 wasm_exec.js:50:14
main.updateUIWithData(0x8a2030, 0x2a) wasm_exec.js:50:14
	/Users/akh/dev/ws2/main.go:142 +0x4 wasm_exec.js:50:14
main.geoJSONToCells(0x0, 0x0, 0x80ed30, 0x1, 0x1, 0x81a1a8, 0x40000000000) wasm_exec.js:50:14
	/Users/akh/dev/ws2/main.go:93 +0x15 wasm_exec.js:50:14
syscall/js.handleEvent() wasm_exec.js:50:14
	/usr/local/Cellar/go/1.15/libexec/src/syscall/js/func.go:96 +0x24
```

**Comment by spreeker** [comment]
Hi  I've notived the regression. I only changed function parameters I will investigate...

**Comment by akhenakh** [comment]
I've fixed it on master

**Pull request merged**
